name: Check GitHub Secrets Configuration

on:
  workflow_dispatch:

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check Required Secrets
      run: |
        echo "🔍 Checking GitHub Secrets Configuration..."
        echo ""
        
        # Check FTP secrets
        if [ -n "${{ secrets.HOSTINGER_FTP_HOST }}" ]; then
          echo "✅ HOSTINGER_FTP_HOST: ${{ secrets.HOSTINGER_FTP_HOST }}"
        else
          echo "❌ HOSTINGER_FTP_HOST: MISSING"
        fi
        
        if [ -n "${{ secrets.HOSTINGER_FTP_USER }}" ]; then
          echo "✅ HOSTINGER_FTP_USER: ${{ secrets.HOSTINGER_FTP_USER }}"
        else
          echo "❌ HOSTINGER_FTP_USER: MISSING"
        fi
        
        if [ -n "${{ secrets.HOSTINGER_FTP_PASS }}" ]; then
          echo "✅ HOSTINGER_FTP_PASS: [CONFIGURED]"
        else
          echo "❌ HOSTINGER_FTP_PASS: MISSING"
        fi
        
        echo ""
        
        # Check SFTP secrets
        if [ -n "${{ secrets.HOSTINGER_SFTP_HOST }}" ]; then
          echo "✅ HOSTINGER_SFTP_HOST: ${{ secrets.HOSTINGER_SFTP_HOST }}"
        else
          echo "⚠️  HOSTINGER_SFTP_HOST: MISSING (optional)"
        fi
        
        if [ -n "${{ secrets.HOSTINGER_SFTP_USER }}" ]; then
          echo "✅ HOSTINGER_SFTP_USER: ${{ secrets.HOSTINGER_SFTP_USER }}"
        else
          echo "⚠️  HOSTINGER_SFTP_USER: MISSING (optional)"
        fi
        
        if [ -n "${{ secrets.HOSTINGER_SFTP_PASS }}" ]; then
          echo "✅ HOSTINGER_SFTP_PASS: [CONFIGURED]"
        else
          echo "⚠️  HOSTINGER_SFTP_PASS: MISSING (optional)"
        fi
        
        echo ""
        echo "📋 Required Secrets for FTP Deployment:"
        echo "   - HOSTINGER_FTP_HOST"
        echo "   - HOSTINGER_FTP_USER" 
        echo "   - HOSTINGER_FTP_PASS"
        echo ""
        echo "📋 Optional Secrets for SFTP Fallback:"
        echo "   - HOSTINGER_SFTP_HOST"
        echo "   - HOSTINGER_SFTP_USER"
        echo "   - HOSTINGER_SFTP_PASS"
        echo ""
        echo "🔧 To add secrets:"
        echo "   1. Go to Repository Settings"
        echo "   2. Click 'Secrets and variables' → 'Actions'"
        echo "   3. Click 'New repository secret'"
        echo "   4. Add each secret with the correct values"
