name: Deploy to Hostinger (SFTP)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies (if any)
      run: |
        if [ -f package.json ]; then
          npm install
        fi
        
    - name: Deploy to Hostinger via SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: ${{ secrets.HOSTINGER_SFTP_HOST }}
        username: ${{ secrets.HOSTINGER_SFTP_USERNAME }}
        password: ${{ secrets.HOSTINGER_SFTP_PASSWORD }}
        local_path: './*'
        remote_path: '/public_html/website2/Krafthaus/'
        exclude: |
          .git*
          .github/
          node_modules/
          README.md
          .DS_Store
          Thumbs.db
          .gitignore
