name: Deploy to Hostinger via SFTP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy via SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: ${{ secrets.HOSTINGER_SFTP_HOST }}
        username: ${{ secrets.HOSTINGER_SFTP_USER }}
        password: ${{ secrets.HOSTINGER_SFTP_PASS }}
        local_path: './*'
        remote_path: '/public_html'
        exclude: |
          .git*
          .github/
          node_modules/
          .DS_Store
          README.md
          deploy-*.sh
          create-*.sh
          webhook.php
          *.md
          .vscode/
          "KraftHaus Website Copy.docx"
          "Krafthaus Logo*.png"
          "Reference.docx"
          "# Code Citations.md"