name: Deploy to Hostinger

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to Hostinger
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.HOSTINGER_FTP_HOST }}
        username: ${{ secrets.HOSTINGER_FTP_USER }}
        password: ${{ secrets.HOSTINGER_FTP_PASS }}
        server-dir: public_html/
        local-dir: ./
        protocol: ftp
        port: 21
        timeout: 60000
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.DS_Store
          **/README.md
          **/.github/**
          **/deploy-*.sh
          **/create-*.sh
          **/webhook.php
          **/*.md
          **/.vscode/**
          **/KraftHaus Website Copy.docx
          **/Krafthaus Logo*.png
          **/Reference.docx
          **/# Code Citations.md
